controller_manager:
  ros__parameters:
    update_rate: 1000  # Hz

    fer_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    fer_gripper_controller:
      type: parallel_gripper_action_controller/GripperActionController

fer_arm_controller:
  ros__parameters:
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    joints:
      - fer_joint1
      - fer_joint2
      - fer_joint3
      - fer_joint4
      - fer_joint5
      - fer_joint6
      - fer_joint7
    gains:
      fer_joint1: { p: 600., d: 30., i: 0., i_clamp: 1. }
      fer_joint2: { p: 600., d: 30., i: 0., i_clamp: 1. }
      fer_joint3: { p: 600., d: 30., i: 0., i_clamp: 1. }
      fer_joint4: { p: 600., d: 30., i: 0., i_clamp: 1. }
      fer_joint5: { p: 250., d: 10., i: 0., i_clamp: 1. }
      fer_joint6: { p: 150., d: 10., i: 0., i_clamp: 1. }
      fer_joint7: { p: 50., d: 5., i: 0., i_clamp: 1. }

fer_gripper_controller:
    ros__parameters:
        action_monitor_rate: 100.0
        allow_stalling: false
        goal_tolerance: 0.01
        joint: 'fer_finger_joint1'
        max_effort: 0.0
        stall_timeout: 1.0
        stall_velocity_threshold: 0.001