# Tell moveit what controllers to use: https://moveit.picknik.ai/main/doc/examples/controller_configuration/controller_configuration_tutorial.html
controller_names:
  - fer_arm_controller
  - fer_gripper_controller

fer_arm_controller:
  action_ns: follow_joint_trajectory
  type: FollowJointTrajectory
  default: true
  joints:
    - fer_joint1
    - fer_joint2
    - fer_joint3
    - fer_joint4
    - fer_joint5
    - fer_joint6
    - fer_joint7

fer_gripper_controller:
    action_ns: gripper_cmd
    type: GripperCommand
    default: true
    joints:
      - fer_finger_joint1
      - fer_finger_joint2
