# Default initial positions for fer's ros2_control fake system

initial_positions:
  fer_finger_joint1: 0
  fer_joint1: 0
  fer_joint2: 0
  fer_joint3: 0
  fer_joint4: 0
  fer_joint5: 0
  fer_joint6: 0
  fer_joint7: 0